# Generated by Django 5.2.5 on 2025-08-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chart of Accounts',
            },
        ),
    ]
