# Generated by Django 5.2.5 on 2025-08-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chartofaccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='category',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='parent_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='formula',
            field=models.TextField(blank=True),
        ),
    ]
