# Generated by Django 5.2.5 on 2025-08-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chartofaccounts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='parent_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
