# Generated by Django 5.2.5 on 2025-08-30 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chartofaccounts_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.CharField(choices=[('actual', 'Actual'), ('budget', 'Budget'), ('forecast', 'Forecast')], max_length=20)),
                ('periods', models.TextField(help_text='JSON list of periods that were backed up')),
                ('backup_data', models.JSONField(help_text='JSON data of all backed up records')),
                ('user', models.CharField(blank=True, help_text='User who made the upload', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_backups', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Data Backups',
                'ordering': ['-backup_date'],
            },
        ),
    ]
