# Generated by Django 5.2.5 on 2025-08-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_databackup'),
    ]

    operations = [
        # Empty migration to fix account types sync
    ]
