# Generated by Django 5.2.5 on 2025-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250831_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='financialdata',
            unique_together={('company', 'account_code', 'period', 'data_type')},
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='parent_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
