# Generated by Django 5.2.5 on 2025-09-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_financialdata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('metric_code', models.CharField(max_length=50, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='CFDashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cfdashboardmetric')),
            ],
            options={
                'ordering': ['period', 'company', 'metric__display_order'],
                'unique_together': {('company', 'period', 'metric')},
            },
        ),
    ]
