# Generated by Django 5.2.5 on 2025-09-02 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_financialdata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_investors', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('redemptions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'ordering': ['period', 'company'],
                'unique_together': {('company', 'period')},
            },
        ),
    ]
