# Generated by Django 5.2.5 on 2025-09-02 01:58

from django.db import migrations

def create_initial_metrics(apps, schema_editor):
    CFDashboardMetric = apps.get_model('core', 'CFDashboardMetric')
    metrics = [
        ('Loans advanced in month', 'loans_advanced', 1),
        ('Loans repaid in month (YTD)', 'loans_repaid_ytd', 2),
        ('Cumulative loan completions (YTD)', 'loan_completions_ytd', 3),
        ('Loan book at month end', 'loan_book_month_end', 4),
        ('Fund LLC', 'fund_llc', 5),
        ('Faes & Co US', 'fund_faes_us', 6),
        ('OakNorth', 'fund_oaknorth', 7),
        ('Triple Point', 'fund_triple_point', 8),
        ('Fund investment received (in mth)', 'fund_investment_received', 9),
    ]
    for name, code, order in metrics:
        CFDashboardMetric.objects.create(
            metric_name=name,
            metric_code=code,
            display_order=order,
            is_active=True,
        )


def reverse_metrics(apps, schema_editor):
    CFDashboardMetric = apps.get_model('core', 'CFDashboardMetric')
    CFDashboardMetric.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cfdashboardmetric_cfdashboarddata'),
    ]

    operations = [
        migrations.RunPython(create_initial_metrics, reverse_metrics),
    ]
