# Generated by Django 5.2.5 on 2025-09-04 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_initial_cf_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDashboardBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_type', models.CharField(choices=[('budget', 'Budget'), ('forecast', 'Forecast')], default='budget', max_length=20)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cfdashboardmetric')),
            ],
            options={
                'ordering': ['period', 'metric__display_order'],
                'unique_together': {('metric', 'period', 'data_type')},
            },
        ),
    ]
