# Generated by Django 5.2.5 on 2025-09-04 23:09

from django.db import migrations


def create_consolidated_company(apps, schema_editor):
    Company = apps.get_model('core', 'Company')
    Company.objects.get_or_create(
        code='CONSOLIDATED',
        defaults={'name': 'Consolidated (Budget/Forecast)'}
    )


def remove_consolidated_company(apps, schema_editor):
    Company = apps.get_model('core', 'Company')
    Company.objects.filter(code='CONSOLIDATED').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cfdashboardbudget'),
    ]

    operations = [
        migrations.RunPython(
            create_consolidated_company,
            remove_consolidated_company,
        ),
    ]
