# Generated by Django 5.2.5 on 2025-09-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_consolidated_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_budget_only',
            field=models.BooleanField(default=False),
        ),
    ]
