# Generated by Django 5.2.5 on 2025-09-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_salary_account',
            field=models.BooleanField(default=False, help_text='Mark if this account represents salary/payroll'),
        ),
    ]
