# Generated by Django 5.2.5 on 2025-09-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_salarydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='is_salary_account',
        ),
    ]
