# Generated by Django 5.2.5 on 2025-09-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_chartofaccounts_is_salary_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestate',
            name='deal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activestate',
            name='deal_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
