# Generated by Django 5.2.5 on 2025-09-18 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_activestate_deal_count_activestate_deal_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(db_index=True, max_length=160)),
                ('column_key', models.CharField(db_index=True, max_length=160)),
                ('row_label', models.CharField(blank=True, max_length=255)),
                ('column_label', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.plcomment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['row_key', 'column_key'], name='core_plcomm_row_key_90d2f2_idx')],
            },
        ),
    ]
