# Generated by Django 5.2.5 on 2025-09-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_plcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(help_text='Scope of the sync (deals, contacts, companies, full, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'HubSpot Sync Log',
                'verbose_name_plural': 'HubSpot Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HubSpotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('deal', 'Deal'), ('company', 'Company'), ('contact', 'Contact')], max_length=20)),
                ('hubspot_id', models.CharField(max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HubSpot Data Record',
                'verbose_name_plural': 'HubSpot Data Records',
                'ordering': ['record_type', 'hubspot_id'],
                'unique_together': {('record_type', 'hubspot_id')},
            },
        ),
    ]
